[package]
name = "protocache-test"
version = "0.1.0"
edition = "2024"

[dependencies]
flatbuffers = "=2.1.2"
prost = "0.13.5"
prost-reflect = "0.15.0"
protocache-core = { path = "../protocache-core" }
protocache-extension = { path = "../protocache-extension" }

[build-dependencies]
prost = "0.13.5"
prost-build = "0.13.5"
prost-types = "0.13.5"
protocache-extension = { path = "../protocache-extension" }
