// @generated by protoc-gen-pcrs.
// Requires the corresponding .pc.rs file to be included first.
use self::test::*;

use protocache_core::{ArrayView, Buffer, EnumValue, FieldView, MutableError, Unit, serialize_message_at};
use protocache_core::mutable::{MutableArray, MutableArrayElement, MutableField, MutableMap, MutableMessage};

#[derive(Clone, Debug, Default)]
pub struct SmallMutable<'a> {
    __view__: MutableMessage<'a, 4, 1>,
    _i32: i32,
    _flag: bool,
    _str: String,
}

impl<'a> SmallMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 4];
        self.__view__.serialize_field(Small::STR_FIELD_ID, &self._str, buffer, &mut parts[Small::STR_FIELD_ID])?;
        self.__view__.serialize_field(Small::FLAG_FIELD_ID, &self._flag, buffer, &mut parts[Small::FLAG_FIELD_ID])?;
        self.__view__.serialize_field(Small::I32_FIELD_ID, &self._i32, buffer, &mut parts[Small::I32_FIELD_ID])?;
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Small".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
    pub fn i32(&mut self) -> &mut i32 {
        self.__view__.get_field(Small::I32_FIELD_ID, &mut self._i32)
    }

    pub fn flag(&mut self) -> &mut bool {
        self.__view__.get_field(Small::FLAG_FIELD_ID, &mut self._flag)
    }

    pub fn str(&mut self) -> &mut String {
        self.__view__.get_field(Small::STR_FIELD_ID, &mut self._str)
    }

}

impl<'a> MutableField<'a> for SmallMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        Small::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { self.__view__.has_any_accessed() }
}

impl<'a> MutableArrayElement<'a> for SmallMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Small".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}

pub type Vec1DMutable<'a> = MutableArray<'a, f32>;

pub type Vec2DMutable<'a> = MutableArray<'a, Vec1DMutable<'a>>;

pub type ArrayMutable<'a> = MutableArray<'a, f32>;

pub type ArrMapMutable<'a> = MutableMap<'a, String, ArrayMutable<'a>>;

#[derive(Clone, Debug, Default)]
pub struct MainMutable<'a> {
    __view__: MutableMessage<'a, 32, 1>,
    _i32: i32,
    _u32: u32,
    _i64: i64,
    _u64: u64,
    _flag: bool,
    _mode: EnumValue,
    _str: String,
    _data: Vec<u8>,
    _f32: f32,
    _f64: f64,
    _object: Box<SmallMutable<'a>>,
    _i32v: MutableArray<'a, i32>,
    _u64v: MutableArray<'a, u64>,
    _strv: MutableArray<'a, String>,
    _datav: MutableArray<'a, Vec<u8>>,
    _f32v: MutableArray<'a, f32>,
    _f64v: MutableArray<'a, f64>,
    _flags: MutableArray<'a, bool>,
    _objectv: MutableArray<'a, SmallMutable<'a>>,
    _t_u32: u32,
    _t_i32: i32,
    _t_s32: i32,
    _t_u64: u64,
    _t_i64: i64,
    _t_s64: i64,
    _index: MutableMap<'a, String, i32>,
    _objects: MutableMap<'a, i32, SmallMutable<'a>>,
    _matrix: Box<Vec2DMutable<'a>>,
    _vector: MutableArray<'a, ArrMapMutable<'a>>,
    _arrays: Box<ArrMapMutable<'a>>,
    _modev: MutableArray<'a, EnumValue>,
}

impl<'a> MainMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 32];
        self.__view__.serialize_field(Main::MODEV_FIELD_ID, &self._modev, buffer, &mut parts[Main::MODEV_FIELD_ID])?;
        self.__view__.serialize_field(Main::ARRAYS_FIELD_ID, &self._arrays, buffer, &mut parts[Main::ARRAYS_FIELD_ID])?;
        self.__view__.serialize_field(Main::VECTOR_FIELD_ID, &self._vector, buffer, &mut parts[Main::VECTOR_FIELD_ID])?;
        self.__view__.serialize_field(Main::MATRIX_FIELD_ID, &self._matrix, buffer, &mut parts[Main::MATRIX_FIELD_ID])?;
        self.__view__.serialize_field(Main::OBJECTS_FIELD_ID, &self._objects, buffer, &mut parts[Main::OBJECTS_FIELD_ID])?;
        self.__view__.serialize_field(Main::INDEX_FIELD_ID, &self._index, buffer, &mut parts[Main::INDEX_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_S64_FIELD_ID, &self._t_s64, buffer, &mut parts[Main::T_S64_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_I64_FIELD_ID, &self._t_i64, buffer, &mut parts[Main::T_I64_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_U64_FIELD_ID, &self._t_u64, buffer, &mut parts[Main::T_U64_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_S32_FIELD_ID, &self._t_s32, buffer, &mut parts[Main::T_S32_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_I32_FIELD_ID, &self._t_i32, buffer, &mut parts[Main::T_I32_FIELD_ID])?;
        self.__view__.serialize_field(Main::T_U32_FIELD_ID, &self._t_u32, buffer, &mut parts[Main::T_U32_FIELD_ID])?;
        self.__view__.serialize_field(Main::OBJECTV_FIELD_ID, &self._objectv, buffer, &mut parts[Main::OBJECTV_FIELD_ID])?;
        self.__view__.serialize_field(Main::FLAGS_FIELD_ID, &self._flags, buffer, &mut parts[Main::FLAGS_FIELD_ID])?;
        self.__view__.serialize_field(Main::F64V_FIELD_ID, &self._f64v, buffer, &mut parts[Main::F64V_FIELD_ID])?;
        self.__view__.serialize_field(Main::F32V_FIELD_ID, &self._f32v, buffer, &mut parts[Main::F32V_FIELD_ID])?;
        self.__view__.serialize_field(Main::DATAV_FIELD_ID, &self._datav, buffer, &mut parts[Main::DATAV_FIELD_ID])?;
        self.__view__.serialize_field(Main::STRV_FIELD_ID, &self._strv, buffer, &mut parts[Main::STRV_FIELD_ID])?;
        self.__view__.serialize_field(Main::U64V_FIELD_ID, &self._u64v, buffer, &mut parts[Main::U64V_FIELD_ID])?;
        self.__view__.serialize_field(Main::I32V_FIELD_ID, &self._i32v, buffer, &mut parts[Main::I32V_FIELD_ID])?;
        self.__view__.serialize_field(Main::OBJECT_FIELD_ID, &self._object, buffer, &mut parts[Main::OBJECT_FIELD_ID])?;
        self.__view__.serialize_field(Main::F64_FIELD_ID, &self._f64, buffer, &mut parts[Main::F64_FIELD_ID])?;
        self.__view__.serialize_field(Main::F32_FIELD_ID, &self._f32, buffer, &mut parts[Main::F32_FIELD_ID])?;
        self.__view__.serialize_field(Main::DATA_FIELD_ID, &self._data, buffer, &mut parts[Main::DATA_FIELD_ID])?;
        self.__view__.serialize_field(Main::STR_FIELD_ID, &self._str, buffer, &mut parts[Main::STR_FIELD_ID])?;
        self.__view__.serialize_field(Main::MODE_FIELD_ID, &self._mode, buffer, &mut parts[Main::MODE_FIELD_ID])?;
        self.__view__.serialize_field(Main::FLAG_FIELD_ID, &self._flag, buffer, &mut parts[Main::FLAG_FIELD_ID])?;
        self.__view__.serialize_field(Main::U64_FIELD_ID, &self._u64, buffer, &mut parts[Main::U64_FIELD_ID])?;
        self.__view__.serialize_field(Main::I64_FIELD_ID, &self._i64, buffer, &mut parts[Main::I64_FIELD_ID])?;
        self.__view__.serialize_field(Main::U32_FIELD_ID, &self._u32, buffer, &mut parts[Main::U32_FIELD_ID])?;
        self.__view__.serialize_field(Main::I32_FIELD_ID, &self._i32, buffer, &mut parts[Main::I32_FIELD_ID])?;
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Main".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
    pub fn i32(&mut self) -> &mut i32 {
        self.__view__.get_field(Main::I32_FIELD_ID, &mut self._i32)
    }

    pub fn u32(&mut self) -> &mut u32 {
        self.__view__.get_field(Main::U32_FIELD_ID, &mut self._u32)
    }

    pub fn i64(&mut self) -> &mut i64 {
        self.__view__.get_field(Main::I64_FIELD_ID, &mut self._i64)
    }

    pub fn u64(&mut self) -> &mut u64 {
        self.__view__.get_field(Main::U64_FIELD_ID, &mut self._u64)
    }

    pub fn flag(&mut self) -> &mut bool {
        self.__view__.get_field(Main::FLAG_FIELD_ID, &mut self._flag)
    }

    pub fn mode(&mut self) -> &mut EnumValue {
        self.__view__.get_field(Main::MODE_FIELD_ID, &mut self._mode)
    }

    pub fn str(&mut self) -> &mut String {
        self.__view__.get_field(Main::STR_FIELD_ID, &mut self._str)
    }

    pub fn data(&mut self) -> &mut Vec<u8> {
        self.__view__.get_field(Main::DATA_FIELD_ID, &mut self._data)
    }

    pub fn f32(&mut self) -> &mut f32 {
        self.__view__.get_field(Main::F32_FIELD_ID, &mut self._f32)
    }

    pub fn f64(&mut self) -> &mut f64 {
        self.__view__.get_field(Main::F64_FIELD_ID, &mut self._f64)
    }

    pub fn object(&mut self) -> &mut SmallMutable<'a> {
        self.__view__.get_field(Main::OBJECT_FIELD_ID, &mut self._object).as_mut()
    }

    pub fn i32v(&mut self) -> &mut MutableArray<'a, i32> {
        self.__view__.get_field(Main::I32V_FIELD_ID, &mut self._i32v)
    }

    pub fn u64v(&mut self) -> &mut MutableArray<'a, u64> {
        self.__view__.get_field(Main::U64V_FIELD_ID, &mut self._u64v)
    }

    pub fn strv(&mut self) -> &mut MutableArray<'a, String> {
        self.__view__.get_field(Main::STRV_FIELD_ID, &mut self._strv)
    }

    pub fn datav(&mut self) -> &mut MutableArray<'a, Vec<u8>> {
        self.__view__.get_field(Main::DATAV_FIELD_ID, &mut self._datav)
    }

    pub fn f32v(&mut self) -> &mut MutableArray<'a, f32> {
        self.__view__.get_field(Main::F32V_FIELD_ID, &mut self._f32v)
    }

    pub fn f64v(&mut self) -> &mut MutableArray<'a, f64> {
        self.__view__.get_field(Main::F64V_FIELD_ID, &mut self._f64v)
    }

    pub fn flags(&mut self) -> &mut MutableArray<'a, bool> {
        self.__view__.get_field(Main::FLAGS_FIELD_ID, &mut self._flags)
    }

    pub fn objectv(&mut self) -> &mut MutableArray<'a, SmallMutable<'a>> {
        self.__view__.get_field(Main::OBJECTV_FIELD_ID, &mut self._objectv)
    }

    pub fn t_u32(&mut self) -> &mut u32 {
        self.__view__.get_field(Main::T_U32_FIELD_ID, &mut self._t_u32)
    }

    pub fn t_i32(&mut self) -> &mut i32 {
        self.__view__.get_field(Main::T_I32_FIELD_ID, &mut self._t_i32)
    }

    pub fn t_s32(&mut self) -> &mut i32 {
        self.__view__.get_field(Main::T_S32_FIELD_ID, &mut self._t_s32)
    }

    pub fn t_u64(&mut self) -> &mut u64 {
        self.__view__.get_field(Main::T_U64_FIELD_ID, &mut self._t_u64)
    }

    pub fn t_i64(&mut self) -> &mut i64 {
        self.__view__.get_field(Main::T_I64_FIELD_ID, &mut self._t_i64)
    }

    pub fn t_s64(&mut self) -> &mut i64 {
        self.__view__.get_field(Main::T_S64_FIELD_ID, &mut self._t_s64)
    }

    pub fn index(&mut self) -> &mut MutableMap<'a, String, i32> {
        self.__view__.get_field(Main::INDEX_FIELD_ID, &mut self._index)
    }

    pub fn objects(&mut self) -> &mut MutableMap<'a, i32, SmallMutable<'a>> {
        self.__view__.get_field(Main::OBJECTS_FIELD_ID, &mut self._objects)
    }

    pub fn matrix(&mut self) -> &mut Vec2DMutable<'a> {
        self.__view__.get_field(Main::MATRIX_FIELD_ID, &mut self._matrix).as_mut()
    }

    pub fn vector(&mut self) -> &mut MutableArray<'a, ArrMapMutable<'a>> {
        self.__view__.get_field(Main::VECTOR_FIELD_ID, &mut self._vector)
    }

    pub fn arrays(&mut self) -> &mut ArrMapMutable<'a> {
        self.__view__.get_field(Main::ARRAYS_FIELD_ID, &mut self._arrays).as_mut()
    }

    pub fn modev(&mut self) -> &mut MutableArray<'a, EnumValue> {
        self.__view__.get_field(Main::MODEV_FIELD_ID, &mut self._modev)
    }

}

impl<'a> MutableField<'a> for MainMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        Main::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { self.__view__.has_any_accessed() }
}

impl<'a> MutableArrayElement<'a> for MainMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Main".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}

#[derive(Clone, Debug, Default)]
pub struct CyclicAMutable<'a> {
    __view__: MutableMessage<'a, 2, 1>,
    _value: i32,
    _cyclic: Box<CyclicBMutable<'a>>,
}

impl<'a> CyclicAMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 2];
        self.__view__.serialize_field(CyclicA::CYCLIC_FIELD_ID, &self._cyclic, buffer, &mut parts[CyclicA::CYCLIC_FIELD_ID])?;
        self.__view__.serialize_field(CyclicA::VALUE_FIELD_ID, &self._value, buffer, &mut parts[CyclicA::VALUE_FIELD_ID])?;
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.CyclicA".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
    pub fn value(&mut self) -> &mut i32 {
        self.__view__.get_field(CyclicA::VALUE_FIELD_ID, &mut self._value)
    }

    pub fn cyclic(&mut self) -> &mut CyclicBMutable<'a> {
        self.__view__.get_field(CyclicA::CYCLIC_FIELD_ID, &mut self._cyclic).as_mut()
    }

}

impl<'a> MutableField<'a> for CyclicAMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        CyclicA::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { self.__view__.has_any_accessed() }
}

impl<'a> MutableArrayElement<'a> for CyclicAMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.CyclicA".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}

#[derive(Clone, Debug, Default)]
pub struct CyclicBMutable<'a> {
    __view__: MutableMessage<'a, 2, 1>,
    _value: i32,
    _cyclic: Box<CyclicAMutable<'a>>,
}

impl<'a> CyclicBMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 2];
        self.__view__.serialize_field(CyclicB::CYCLIC_FIELD_ID, &self._cyclic, buffer, &mut parts[CyclicB::CYCLIC_FIELD_ID])?;
        self.__view__.serialize_field(CyclicB::VALUE_FIELD_ID, &self._value, buffer, &mut parts[CyclicB::VALUE_FIELD_ID])?;
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.CyclicB".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
    pub fn value(&mut self) -> &mut i32 {
        self.__view__.get_field(CyclicB::VALUE_FIELD_ID, &mut self._value)
    }

    pub fn cyclic(&mut self) -> &mut CyclicAMutable<'a> {
        self.__view__.get_field(CyclicB::CYCLIC_FIELD_ID, &mut self._cyclic).as_mut()
    }

}

impl<'a> MutableField<'a> for CyclicBMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        CyclicB::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { self.__view__.has_any_accessed() }
}

impl<'a> MutableArrayElement<'a> for CyclicBMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.CyclicB".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}

#[derive(Clone, Debug, Default)]
pub struct DeprecatedValidMutable<'a> {
    __view__: MutableMessage<'a, 1, 1>,
    _val: i32,
}

impl<'a> DeprecatedValidMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 1];
        self.__view__.serialize_field(DeprecatedValid::VAL_FIELD_ID, &self._val, buffer, &mut parts[DeprecatedValid::VAL_FIELD_ID])?;
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Deprecated.Valid".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
    pub fn val(&mut self) -> &mut i32 {
        self.__view__.get_field(DeprecatedValid::VAL_FIELD_ID, &mut self._val)
    }

}

impl<'a> MutableField<'a> for DeprecatedValidMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        DeprecatedValid::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { self.__view__.has_any_accessed() }
}

impl<'a> MutableArrayElement<'a> for DeprecatedValidMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Deprecated.Valid".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}

#[derive(Clone, Debug, Default)]
pub struct DeprecatedMutable<'a> {
    __view__: MutableMessage<'a, 0, 0>,
}

impl<'a> DeprecatedMutable<'a> {
    pub fn New() -> Self { Self::default() }
    pub fn FromWords(words: &'a [u32]) -> Option<Self> {
        Some(Self { __view__: MutableMessage::from_words(words)?, ..Self::default() })
    }
    pub fn HasField(&self, id: usize) -> bool { self.__view__.has_field(id) }
    fn EncodeToUnit(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if let Some(words) = self.__view__.clean_words() {
            return Ok(protocache_core::mutable::copy_words(words, buffer, false));
        }
        let last = buffer.len();
        let mut parts = [Unit::empty(); 0];
        serialize_message_at(&mut parts, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Deprecated".to_owned(),
            field: "<message>".to_owned(),
        })
    }
    pub fn SerializeWords(&self) -> Result<Vec<u32>, MutableError> {
        let mut buffer = Buffer::new();
        let _ = self.SerializeIntoBuffer(&mut buffer)?;
        Ok(buffer.view().to_vec())
    }
    pub fn SerializeIntoBuffer<'b>(&self, buffer: &'b mut Buffer) -> Result<&'b [u32], MutableError> {
        buffer.clear();
        let _ = self.EncodeToUnit(buffer)?;
        Ok(buffer.view())
    }
}

impl<'a> MutableField<'a> for DeprecatedMutable<'a> {
    fn decode(field: FieldView<'a>) -> Option<Self> {
        Self::FromWords(field.object_words()?)
    }
    fn detect<'b>(field: FieldView<'b>) -> Option<&'b [u32]> {
        Deprecated::Detect(field.object_words()?)
    }
    fn encode(&self, buffer: &mut Buffer) -> Result<Unit, MutableError> {
        self.EncodeToUnit(buffer)
    }
    fn is_dirty(&self) -> bool { false }
}

impl<'a> MutableArrayElement<'a> for DeprecatedMutable<'a> {
    fn decode_array(words: &'a [u32]) -> Option<Vec<Self>> {
        let array = ArrayView::new(words)?;
        let mut values = Vec::with_capacity(array.len());
        for item in array.iter() { values.push(Self::FromWords(item.object_words()?)?); }
        Some(values)
    }
    fn encode_array(values: &[Self], buffer: &mut Buffer) -> Result<Unit, MutableError> {
        if values.is_empty() { return Ok(Unit::inline(&[1])); }
        let last = buffer.len();
        let mut units = vec![Unit::empty(); values.len()];
        for i in (0..values.len()).rev() { units[i] = values[i].encode(buffer)?; }
        protocache_core::serialize_array_at_mut(&mut units, buffer, last).ok_or_else(|| MutableError::SerializeFailed {
            descriptor: ".test.Deprecated".to_owned(),
            field: "<array>".to_owned(),
        })
    }
}
