// @generated by protoc-gen-pcrs.
pub mod test {

    use protocache_core::{ArrayView, BoolArray, EnumValue, FieldDecode, FieldView, MapView, MessageView, ScalarArray, StringView, ViewArray, ViewMap};

    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    #[allow(non_camel_case_types)]
    #[repr(i32)]
    pub enum Mode {
        MODE_A = 0,
        MODE_B = 1,
        MODE_C = 2,
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Small<'a> {
        view: MessageView<'a>,
    }

    impl<'a> Small<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            let core = MessageView::new(words)?;
            if let Some(field) = core.field(Self::STR_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_string()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }

        pub const I32_FIELD_ID: usize = 0;
        pub const FLAG_FIELD_ID: usize = 1;
        pub const STR_FIELD_ID: usize = 3;

        pub fn i32(self) -> i32 {
            self.view.scalar::<i32>(Self::I32_FIELD_ID).unwrap_or_default()
        }

        pub fn flag(self) -> bool {
            self.view.scalar::<bool>(Self::FLAG_FIELD_ID).unwrap_or(false)
        }

        pub fn str(self) -> Option<&'a str> {
            self.view.string(Self::STR_FIELD_ID)?.as_str()
        }

    }

    impl<'a> FieldDecode<'a> for Small<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Vec1D<'a> {
        view: ArrayView<'a>,
    }

    impl<'a> Vec1D<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: ArrayView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            ArrayView::detect_len(words)
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn values(self) -> ScalarArray<'a, f32> {
            self.view.scalars::<f32>().expect("generated alias invariant violated: Vec1D")
        }
    }

    impl<'a> FieldDecode<'a> for Vec1D<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Self::FromWords(field.object_words()?)
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Vec2D<'a> {
        view: ArrayView<'a>,
    }

    impl<'a> Vec2D<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: ArrayView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            Some(protocache_core::detect_array_with(words, |item| Vec1D::Detect(item.object_words()?))?.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn values(self) -> ViewArray<'a, Vec1D<'a>> {
            ViewArray::new(self.view)
        }
    }

    impl<'a> FieldDecode<'a> for Vec2D<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Self::FromWords(field.object_words()?)
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Array<'a> {
        view: ArrayView<'a>,
    }

    impl<'a> Array<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: ArrayView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            ArrayView::detect_len(words)
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn values(self) -> ScalarArray<'a, f32> {
            self.view.scalars::<f32>().expect("generated alias invariant violated: Array")
        }
    }

    impl<'a> FieldDecode<'a> for Array<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Self::FromWords(field.object_words()?)
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct ArrMap<'a> {
        view: MapView<'a>,
    }

    impl<'a> ArrMap<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MapView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            Some(protocache_core::detect_map_with(words, |key| key.detect_string(), |value| Array::Detect(value.object_words()?))?.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn entries(self) -> ViewMap<'a, StringView<'a>, Array<'a>> {
            ViewMap::new(self.view)
        }
    }

    impl<'a> FieldDecode<'a> for ArrMap<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Self::FromWords(field.object_words()?)
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Main<'a> {
        view: MessageView<'a>,
    }

    impl<'a> Main<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            let core = MessageView::new(words)?;
            if let Some(field) = core.field(Self::MODEV_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_array()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::ARRAYS_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, ArrMap::Detect(field.object_words()?)?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::VECTOR_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_array_with(field.object_words()?, |item| ArrMap::Detect(item.object_words()?))?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::MATRIX_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, Vec2D::Detect(field.object_words()?)?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::OBJECTS_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_map_with(field.object_words()?, |key| key.detect_scalar(), |value| Small::Detect(value.object_words()?))?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::INDEX_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_map_with(field.object_words()?, |key| key.detect_string(), |value| value.detect_scalar())?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::OBJECTV_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_array_with(field.object_words()?, |item| Small::Detect(item.object_words()?))?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::FLAGS_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_string()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::F64V_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_array()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::F32V_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_array()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::DATAV_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_array_with(field.object_words()?, |item| item.detect_string())?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::STRV_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, protocache_core::detect_array_with(field.object_words()?, |item| item.detect_string())?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::U64V_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_array()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::I32V_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_array()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::OBJECT_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, Small::Detect(field.object_words()?)?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::DATA_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_string()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            if let Some(field) = core.field(Self::STR_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, field.detect_string()?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }

        pub const I32_FIELD_ID: usize = 0;
        pub const U32_FIELD_ID: usize = 1;
        pub const I64_FIELD_ID: usize = 2;
        pub const U64_FIELD_ID: usize = 3;
        pub const FLAG_FIELD_ID: usize = 4;
        pub const MODE_FIELD_ID: usize = 5;
        pub const STR_FIELD_ID: usize = 6;
        pub const DATA_FIELD_ID: usize = 7;
        pub const F32_FIELD_ID: usize = 8;
        pub const F64_FIELD_ID: usize = 9;
        pub const OBJECT_FIELD_ID: usize = 10;
        pub const I32V_FIELD_ID: usize = 11;
        pub const U64V_FIELD_ID: usize = 12;
        pub const STRV_FIELD_ID: usize = 13;
        pub const DATAV_FIELD_ID: usize = 14;
        pub const F32V_FIELD_ID: usize = 15;
        pub const F64V_FIELD_ID: usize = 16;
        pub const FLAGS_FIELD_ID: usize = 17;
        pub const OBJECTV_FIELD_ID: usize = 18;
        pub const T_U32_FIELD_ID: usize = 19;
        pub const T_I32_FIELD_ID: usize = 20;
        pub const T_S32_FIELD_ID: usize = 21;
        pub const T_U64_FIELD_ID: usize = 22;
        pub const T_I64_FIELD_ID: usize = 23;
        pub const T_S64_FIELD_ID: usize = 24;
        pub const INDEX_FIELD_ID: usize = 25;
        pub const OBJECTS_FIELD_ID: usize = 26;
        pub const MATRIX_FIELD_ID: usize = 27;
        pub const VECTOR_FIELD_ID: usize = 28;
        pub const ARRAYS_FIELD_ID: usize = 29;
        pub const MODEV_FIELD_ID: usize = 31;

        pub fn i32(self) -> i32 {
            self.view.scalar::<i32>(Self::I32_FIELD_ID).unwrap_or_default()
        }

        pub fn u32(self) -> u32 {
            self.view.scalar::<u32>(Self::U32_FIELD_ID).unwrap_or_default()
        }

        pub fn i64(self) -> i64 {
            self.view.scalar::<i64>(Self::I64_FIELD_ID).unwrap_or_default()
        }

        pub fn u64(self) -> u64 {
            self.view.scalar::<u64>(Self::U64_FIELD_ID).unwrap_or_default()
        }

        pub fn flag(self) -> bool {
            self.view.scalar::<bool>(Self::FLAG_FIELD_ID).unwrap_or(false)
        }

        pub fn mode(self) -> EnumValue {
            self.view.scalar::<EnumValue>(Self::MODE_FIELD_ID).unwrap_or_default()
        }

        pub fn str(self) -> Option<&'a str> {
            self.view.string(Self::STR_FIELD_ID)?.as_str()
        }

        pub fn data(self) -> Option<&'a [u8]> {
            self.view.bytes(Self::DATA_FIELD_ID)
        }

        pub fn f32(self) -> f32 {
            self.view.scalar::<f32>(Self::F32_FIELD_ID).unwrap_or_default()
        }

        pub fn f64(self) -> f64 {
            self.view.scalar::<f64>(Self::F64_FIELD_ID).unwrap_or_default()
        }

        pub fn object(self) -> Option<Small<'a>> {
            Some(Small { view: self.view.message(Self::OBJECT_FIELD_ID)? })
        }

        pub fn i32v(self) -> Option<ScalarArray<'a, i32>> {
            self.view.array(Self::I32V_FIELD_ID)?.scalars::<i32>()
        }

        pub fn u64v(self) -> Option<ScalarArray<'a, u64>> {
            self.view.array(Self::U64V_FIELD_ID)?.scalars::<u64>()
        }

        pub fn strv(self) -> Option<ViewArray<'a, StringView<'a>>> {
            Some(ViewArray::new(self.view.array(Self::STRV_FIELD_ID)?))
        }

        pub fn datav(self) -> Option<ViewArray<'a, StringView<'a>>> {
            Some(ViewArray::new(self.view.array(Self::DATAV_FIELD_ID)?))
        }

        pub fn f32v(self) -> Option<ScalarArray<'a, f32>> {
            self.view.array(Self::F32V_FIELD_ID)?.scalars::<f32>()
        }

        pub fn f64v(self) -> Option<ScalarArray<'a, f64>> {
            self.view.array(Self::F64V_FIELD_ID)?.scalars::<f64>()
        }

        pub fn flags(self) -> Option<BoolArray<'a>> {
            self.view.bools(Self::FLAGS_FIELD_ID)
        }

        pub fn objectv(self) -> Option<ViewArray<'a, Small<'a>>> {
            Some(ViewArray::new(self.view.array(Self::OBJECTV_FIELD_ID)?))
        }

        pub fn t_u32(self) -> u32 {
            self.view.scalar::<u32>(Self::T_U32_FIELD_ID).unwrap_or_default()
        }

        pub fn t_i32(self) -> i32 {
            self.view.scalar::<i32>(Self::T_I32_FIELD_ID).unwrap_or_default()
        }

        pub fn t_s32(self) -> i32 {
            self.view.scalar::<i32>(Self::T_S32_FIELD_ID).unwrap_or_default()
        }

        pub fn t_u64(self) -> u64 {
            self.view.scalar::<u64>(Self::T_U64_FIELD_ID).unwrap_or_default()
        }

        pub fn t_i64(self) -> i64 {
            self.view.scalar::<i64>(Self::T_I64_FIELD_ID).unwrap_or_default()
        }

        pub fn t_s64(self) -> i64 {
            self.view.scalar::<i64>(Self::T_S64_FIELD_ID).unwrap_or_default()
        }

        pub fn index(self) -> Option<ViewMap<'a, StringView<'a>, i32>> {
            Some(ViewMap::new(self.view.map(Self::INDEX_FIELD_ID)?))
        }

        pub fn objects(self) -> Option<ViewMap<'a, i32, Small<'a>>> {
            Some(ViewMap::new(self.view.map(Self::OBJECTS_FIELD_ID)?))
        }

        pub fn matrix(self) -> Option<Vec2D<'a>> {
            Vec2D::FromWords(self.view.field(Self::MATRIX_FIELD_ID)?.object_words()?)
        }

        pub fn vector(self) -> Option<ViewArray<'a, ArrMap<'a>>> {
            Some(ViewArray::new(self.view.array(Self::VECTOR_FIELD_ID)?))
        }

        pub fn arrays(self) -> Option<ArrMap<'a>> {
            ArrMap::FromWords(self.view.field(Self::ARRAYS_FIELD_ID)?.object_words()?)
        }

        pub fn modev(self) -> Option<ScalarArray<'a, EnumValue>> {
            self.view.array(Self::MODEV_FIELD_ID)?.scalars::<EnumValue>()
        }

    }

    impl<'a> FieldDecode<'a> for Main<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct CyclicA<'a> {
        view: MessageView<'a>,
    }

    impl<'a> CyclicA<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            let core = MessageView::new(words)?;
            if let Some(field) = core.field(Self::CYCLIC_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, CyclicB::Detect(field.object_words()?)?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }

        pub const VALUE_FIELD_ID: usize = 0;
        pub const CYCLIC_FIELD_ID: usize = 1;

        pub fn value(self) -> i32 {
            self.view.scalar::<i32>(Self::VALUE_FIELD_ID).unwrap_or_default()
        }

        pub fn cyclic(self) -> Option<CyclicB<'a>> {
            Some(CyclicB { view: self.view.message(Self::CYCLIC_FIELD_ID)? })
        }

    }

    impl<'a> FieldDecode<'a> for CyclicA<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct CyclicB<'a> {
        view: MessageView<'a>,
    }

    impl<'a> CyclicB<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            let core = MessageView::new(words)?;
            if let Some(field) = core.field(Self::CYCLIC_FIELD_ID) {
                let mut end = view.len();
                protocache_core::detect_slice_end(words, CyclicA::Detect(field.object_words()?)?, &mut end)?;
                if end > view.len() {
                    return Some(end);
                }
            }
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }

        pub const VALUE_FIELD_ID: usize = 0;
        pub const CYCLIC_FIELD_ID: usize = 1;

        pub fn value(self) -> i32 {
            self.view.scalar::<i32>(Self::VALUE_FIELD_ID).unwrap_or_default()
        }

        pub fn cyclic(self) -> Option<CyclicA<'a>> {
            Some(CyclicA { view: self.view.message(Self::CYCLIC_FIELD_ID)? })
        }

    }

    impl<'a> FieldDecode<'a> for CyclicB<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct DeprecatedValid<'a> {
        view: MessageView<'a>,
    }

    impl<'a> DeprecatedValid<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            let core = MessageView::new(words)?;
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }

        pub const VAL_FIELD_ID: usize = 0;

        pub fn val(self) -> i32 {
            self.view.scalar::<i32>(Self::VAL_FIELD_ID).unwrap_or_default()
        }

    }

    impl<'a> FieldDecode<'a> for DeprecatedValid<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

    #[derive(Clone, Copy, Debug)]
    pub struct Deprecated<'a> {
        view: MessageView<'a>,
    }

    impl<'a> Deprecated<'a> {
        pub fn FromWords(words: &'a [u32]) -> Option<Self> {
            Some(Self { view: MessageView::new(words)? })
        }
        fn DetectLen(words: &'a [u32]) -> Option<usize> {
            let view = MessageView::detect(words)?;
            Some(view.len())
        }
        pub fn Detect(words: &'a [u32]) -> Option<&'a [u32]> {
            Some(words.get(..Self::DetectLen(words)?)?)
        }
        pub fn HasField(self, id: usize) -> bool { self.view.has_field(id) }


    }

    impl<'a> FieldDecode<'a> for Deprecated<'a> {
        fn decode(field: FieldView<'a>) -> Option<Self> {
            Some(Self { view: field.message()? })
        }
    }

} // mod test
