[package]
name = "protoc-gen-pcrs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
documentation = "https://docs.rs/protoc-gen-pcrs"
description = "protoc plugin generating typed Rust bindings for ProtoCache"
keywords = ["protobuf", "protoc", "serialization", "codegen"]
categories = ["development-tools::build-utils", "encoding"]

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
protocache-core = { version = "0.1.1", path = "../protocache-core" }
protocache-extension = { version = "0.1.1", path = "../protocache-extension" }

[dev-dependencies]
protocache-extension = { version = "0.1.1", path = "../protocache-extension" }
