[package]
name = "protoc-gen-pcrs"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.13.5"
prost-types = "0.13.5"
protocache-core = { path = "../protocache-core" }
protocache-extension = { path = "../protocache-extension" }

[dev-dependencies]
protocache-extension = { path = "../protocache-extension" }
